services:
  backend:
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./backend/app:/app/app
    command: >
      uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    ports:
      - "5432:5432"

  telegram-bot:
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./telegram-bot:/app
    command: >
      uv run python bot.py
